<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNQbu5YU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNQbu5YU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNQbu5YU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNQbu5YU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNQbu5YU\App_KernelDevDebugContainer([
    'container.build_hash' => 'NQbu5YU',
    'container.build_id' => '69abb8af',
    'container.build_time' => 1764943122,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNQbu5YU');
